<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-MPU386I" failures="1" tests="6" name="webdriver.Topic_03_Xpath_Part3" time="11.957" errors="0" timestamp="26 Dec 2022 09:49:06 GMT" skipped="0">
  <testcase classname="webdriver.Topic_03_Xpath_Part3" name="TC_03_Incorrect_Email" time="1.007"/>
  <testcase classname="webdriver.Topic_03_Xpath_Part3" name="TC_01_Empty_Data" time="4.770"/>
  <testcase classname="webdriver.Topic_03_Xpath_Part3" name="TC_06_Invalid_Phone" time="2.367"/>
  <testcase classname="webdriver.Topic_03_Xpath_Part3" name="TC_02_Invalid_Email" time="1.677">
    <failure message="expected [Vui lòng nhập email hợp lệ] but found [Email nhập lại không đúng]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [Vui lòng nhập email hợp lệ] but found [Email nhập lại không đúng]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at webdriver.Topic_03_Xpath_Part3.TC_02_Invalid_Email(Topic_03_Xpath_Part3.java:51)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- TC_02_Invalid_Email -->
  <testcase classname="webdriver.Topic_03_Xpath_Part3" name="TC_04_Invalid_Password" time="1.126"/>
  <testcase classname="webdriver.Topic_03_Xpath_Part3" name="TC_05_Incorrect_Password" time="1.010"/>
</testsuite> <!-- webdriver.Topic_03_Xpath_Part3 -->
